### ISSUE TITLE
Missing `pg_config` doesn't fail the build

### ISSUE THREAD

**Issue by marshallpierce** [posix4e/rpgffi#4]
When `pg_config` is not on the path, `choose_postgresql_version` emits this:

```
./util/choose_postgresql_version: line 4: pg_config: command not found
```

It then proceeds to execute the rest of the script with the `pg_short_version` set to empty string. This is because of the confusing behavior around subshells and `-e` mode in shell scripts. 

There are various painful approaches to trying to make subshells honor `-e` (see plenty of StackOverflow questions) but the simplest seems to break out the call to `pg_config`, like this:

```
pg_long_version=`pg_config --version`
pg_short_version=pg"`echo -n $pg_long_version | cut -d' ' -f2 | tr -d . | cut -c-2`"
```

If this seems OK to you, I'd be happy to make a PR with this small change. A more sophisticated approach would be to simply do it in `build.rs` of course...

**Comment by posix4e** [comment]
I'd love a PR

**Comment by marshallpierce** [comment]
done. https://github.com/posix4e/rpgffi/pull/5
