### ISSUE TITLE
Figure out a way to get the generated files out of the git history

### ISSUE THREAD

**Issue by posix4e** [posix4e/rpgffi#8]
We have a few options here.

- WIth modern rust maybe we generate and push from travis.
- large file support git

**Comment by durch** [comment]
Something like  [git filter-branch](https://git-scm.com/docs/git-filter-branch) can do the trick of removing... I'll see about doing a PR...

**Comment by durch** [comment]
Basicly done, will do some more checks tomorrow, but I have something push ready...

The idea is to make a commit that deletes `pg*.rs` files and adds them to `.gitignore`, after that is done, [bfg](https://rtyley.github.io/bfg-repo-cleaner/) will be used to permenantly purge history...

Thoughts and critiques welcome :)

**Comment by posix4e** [comment]
We should wait til the next jsoncdc release. But I totally agree. Mind if we wait on this a week? Or feel free to squeeze it in if you already did it.

**Comment by durch** [comment]
Not at all, I'll do a fork and cleanup there, just so that we can see how it would look, and than we can  propagate in 2017 :)
